import { useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Database, FileText, FlaskConical, Layers3, Microscope, Sparkles, X } from "lucide-react";

export function ResearchHome({onOpen}:{onOpen:()=>void}){
  const initialProjects = [
    ["短视频平台与大学生冲动消费","学位论文课题","开题中 · 35%","10月12日完成开题",FlaskConical],
    ["社会比较与青年消费行为","文献综述","整理中 · 18篇文献","本周完成理论框架",BookOpen],
    ["大学生短视频使用预测试","调查研究","数据收集中 · 24/30","还差6份有效问卷",Microscope],
    ["推荐算法暴露与购买决策","自主研究","构思中","已发现3个研究问题",Layers3],
    ["青年数字媒介使用数据库","数据项目","建设中 · 120条记录","本周新增18条",Database],
  ];
  const researchTypes = [["学位论文","适合硕博论文与毕业研究"],["课程论文","围绕课程形成规范论文"],["文献综述","梳理领域、观点与研究空白"],["调查／实验研究","从问题推进到数据验证"],["数据项目","建设数据集并持续分析"],["自主探索","从一个模糊问题开始生长"]];
  const [projects,setProjects]=useState(initialProjects);
  const [creating,setCreating]=useState(false);
  const [step,setStep]=useState(1);
  const [type,setType]=useState("学位论文");
  const [intent,setIntent]=useState("");
  const suggestedTitle=intent.trim()||"生成式 AI 对大学生学术写作的影响";
  const close=()=>{setCreating(false);setStep(1);setIntent("");setType("学位论文")};
  const create=()=>{setProjects(p=>[[suggestedTitle,type,"已创建 · 0%","确认研究问题",type.includes("数据")?Database:type.includes("综述")?BookOpen:FlaskConical],...p]);close()};
  return <div className="h-full overflow-y-auto px-8 py-7"><p className="text-[11px] font-bold tracking-[.12em] text-[#8C93A3]">研究工作台</p><div className="mt-2 flex items-end"><div><h1 className="text-[28px] font-bold">研究</h1><p className="mt-1 text-[13px] text-[#7B8291]">从长期方向发展课题，并逐步形成论文、数据与研究成果。</p></div><button onClick={()=>setCreating(true)} className="ml-auto rounded-xl bg-[#4D5CFF] px-4 py-2 text-[12px] font-semibold text-white">+ 新建研究</button></div>
    <section className="mt-7 rounded-2xl border border-[#DDE1FF] bg-gradient-to-r from-[#F5F6FF] to-white p-5"><div className="flex items-center"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#4D5CFF] text-white"><Layers3 size={19}/></span><div className="ml-3"><small className="text-[#7B8291]">研究方向</small><h2 className="text-[16px] font-bold">数字媒介与青年消费</h2></div><div className="ml-auto text-right"><b className="text-[13px] text-[#4D5CFF]">5 个课题 · 3 项成果</b><p className="text-[10px] text-[#9CA3AF]">持续积累 26 条相关知识</p></div></div></section>
    <div className="mt-6 flex items-center"><h2 className="text-[15px] font-bold">正在研究 · {projects.length}</h2></div><div className="mt-3 grid grid-cols-2 gap-3">{projects.map(x=>{const Icon=x[4] as typeof BookOpen;const openable=x[0]==="短视频平台与大学生冲动消费";return <button key={x[0] as string} disabled={!openable} onClick={openable?onOpen:undefined} className={`rounded-2xl border border-[#E7EAF0] bg-white p-5 text-left ${openable?"hover:border-[#BEC5FF]":"cursor-default"}`}><div className="flex items-start"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#EEF0FF] text-[#4D5CFF]"><Icon size={18}/></span><span className="ml-auto rounded-full bg-[#F4F5F8] px-2 py-1 text-[10px] text-[#7B8291]">{x[1] as string}</span></div><b className="mt-4 block text-[14px]">{x[0] as string}</b><p className="mt-1 text-[11px] text-[#4D5CFF]">{x[2] as string}</p><div className="mt-4 flex items-center border-t border-[#F0F1F5] pt-3"><small className="text-[#8A909C]">下一步：{x[3] as string}</small>{openable&&<ArrowRight size={14} className="ml-auto text-[#4D5CFF]"/>}</div></button>})}</div>
    <div className="mt-7 flex items-center"><h2 className="text-[15px] font-bold">近期产出</h2></div><div className="mt-3 grid grid-cols-3 gap-3">{[["学位论文","撰写准备"],["开题报告","编辑中 · 35%"],["调查问卷","初稿 · 待预测试"]].map(x=><div key={x[0]} className="rounded-2xl border border-[#E7EAF0] bg-white p-4"><FileText size={17} className="text-[#4D5CFF]"/><b className="mt-3 block text-[13px]">{x[0]}</b><p className="mt-1 text-[10px] text-[#8A909C]">{x[1]}</p></div>)}</div>
    <div className="mt-7"><h2 className="text-[15px] font-bold">跨阶段延展样例</h2><p className="mt-1 text-[11px] text-[#8A909C]">同一套研究记忆结构，不增加导航，也能延展到硕士与博士阶段。</p></div><div className="mt-3 grid grid-cols-2 gap-3">{[["硕士阶段","推荐机制、社会比较与消费决策","已形成文献矩阵 · 方法训练中","课程论文、开题与学位论文共享 31 条知识"],["博士阶段","平台化消费的长期追踪研究","第二轮数据收集 · 论文返修中","资格考试、会议报告与投稿共享证据链"]].map(x=><div key={x[0]} className="rounded-2xl border border-[#E7EAF0] bg-white p-4"><span className="rounded-full bg-[#F1F3FF] px-2 py-1 text-[10px] font-semibold text-[#4D5CFF]">{x[0]}</span><b className="mt-3 block text-[13px]">{x[1]}</b><p className="mt-1 text-[11px] text-[#626977]">{x[2]}</p><p className="mt-3 text-[10px] text-[#9CA3AF]">{x[3]}</p></div>)}</div>
    {creating&&<div className="fixed inset-0 z-[200] bg-[#171A24]/30" onClick={close}><aside onClick={e=>e.stopPropagation()} className="ml-auto flex h-full w-[520px] flex-col bg-[#FAFBFD] shadow-2xl"><header className="border-b border-[#E7EAF0] bg-white px-6 py-5"><div className="flex items-center"><div><p className="text-[10px] font-bold tracking-[.12em] text-[#8C93A3]">新建研究 · {step}/3</p><h2 className="mt-1 text-[20px] font-bold">{step===1?"这次想开展什么研究？":step===2?"描述你的研究想法":"确认研究方案"}</h2></div><button onClick={close} className="ml-auto grid h-8 w-8 place-items-center rounded-lg hover:bg-[#F4F5F8]"><X size={17}/></button></div><div className="mt-4 flex gap-2">{[1,2,3].map(i=><span key={i} className={`h-1 flex-1 rounded-full ${i<=step?"bg-[#4D5CFF]":"bg-[#E7EAF0]"}`}/>)}</div></header><div className="flex-1 overflow-y-auto p-6">
      {step===1&&<div className="grid grid-cols-2 gap-3">{researchTypes.map(x=><button key={x[0]} onClick={()=>setType(x[0])} className={`rounded-2xl border p-4 text-left ${type===x[0]?"border-[#4D5CFF] bg-[#F1F3FF]":"border-[#E7EAF0] bg-white"}`}><b className="text-[13px]">{x[0]}</b><p className="mt-2 text-[11px] leading-5 text-[#7B8291]">{x[1]}</p>{type===x[0]&&<CheckCircle2 className="mt-3 text-[#4D5CFF]" size={16}/>}</button>)}</div>}
      {step===2&&<div><div className="rounded-2xl border border-[#E7EAF0] bg-white p-4"><label className="text-[12px] font-bold">用一句话描述你想研究的问题</label><textarea autoFocus value={intent} onChange={e=>setIntent(e.target.value)} placeholder="例如：我想研究生成式 AI 对大学生写作能力的影响" className="mt-3 h-32 w-full resize-none rounded-xl bg-[#F7F8FB] p-3 text-[13px] outline-none placeholder:text-[#B0B5C0]"/><p className="mt-2 text-[10px] text-[#9CA3AF]">不需要先想好标题，AI 会结合长期知识生成初步方案。</p></div><div className="mt-4 flex gap-3 rounded-2xl bg-[#F1F3FF] p-4 text-[#4D5CFF]"><Sparkles size={18}/><p className="text-[11px] leading-5">将自动关联已有知识、相关原始资料，并生成研究问题和第一步行动。</p></div></div>}
      {step===3&&<div className="space-y-3"><div className="rounded-2xl border border-[#DDE1FF] bg-white p-5"><div className="flex items-center gap-2"><Sparkles size={16} className="text-[#4D5CFF]"/><small className="font-semibold text-[#4D5CFF]">AI 生成的可编辑方案</small></div><h3 className="mt-4 text-[17px] font-bold">{suggestedTitle}</h3><span className="mt-2 inline-block rounded-full bg-[#F1F3FF] px-2 py-1 text-[10px] text-[#4D5CFF]">{type}</span></div>{[["研究问题","该因素如何影响目标群体？其作用机制和边界条件是什么？"],["已有知识","已找到 8 条相关知识、3 份原始资料"],["第一步行动","确认研究范围，并阅读 AI 推荐的 3 份核心资料"],["预期成果",type.includes("数据")?"可复用数据集与分析报告":type.includes("综述")?"文献矩阵与综述初稿":"研究方案、阶段报告与最终论文"]].map(x=><div key={x[0]} className="rounded-2xl border border-[#E7EAF0] bg-white p-4"><small className="font-semibold text-[#8A909C]">{x[0]}</small><p className="mt-2 text-[12px] leading-5">{x[1]}</p></div>)}</div>}
    </div><footer className="flex items-center border-t border-[#E7EAF0] bg-white p-5">{step>1&&<button onClick={()=>setStep(step-1)} className="flex items-center gap-1 rounded-xl px-4 py-2 text-[12px] font-semibold text-[#626977]"><ArrowLeft size={14}/>上一步</button>}<button disabled={step===2&&!intent.trim()} onClick={()=>step<3?setStep(step+1):create()} className="ml-auto rounded-xl bg-[#4D5CFF] px-5 py-2.5 text-[12px] font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{step===1?"下一步":step===2?"生成研究方案":"确认并创建"}</button></footer></aside></div>}
  </div>;
}

export function ResearchWorkspace({children}:{children:React.ReactNode;onAddSource:()=>void}){
  return <div className="flex min-h-0 flex-1 flex-col">{children}</div>;
}
