import {useState} from "react";
import {Plus,Search,Sparkles,SunMedium} from "lucide-react";
import {imgLoadingSpinner} from "../../data/initialData";
import type {SubjectData} from "../../types";
import type {ScenarioPackage} from "../../scenarios/types";

export type WorkspaceId="today"|"activity"|"inbox"|"knowledge"|"course"|"project"|"goals"|"sources";
const colors=["#4D5CFF","#10B981","#F59E0B","#EC4899","#8B5CF6"];

export function Sidebar({activeWorkspace,activeSubject,onSelectWorkspace,onSelectSubject,isLoading,subjects,onOpenSearch,onUploadFile,todayCount,scenario}:{activeWorkspace:WorkspaceId;activeSubject:string;onSelectWorkspace:(id:WorkspaceId)=>void;onSelectSubject:(id:string)=>void;isLoading:boolean;subjects:SubjectData[];onOpenSearch:()=>void;onUploadFile:()=>void;todayCount:number;scenario:ScenarioPackage}){
 const [profileOpen,setProfileOpen]=useState(false); const [profileCorrected,setProfileCorrected]=useState(false); const [evidenceOpen,setEvidenceOpen]=useState(false); const p=scenario.userProfile;
 const navButton=(id:WorkspaceId,label:string,Icon:typeof SunMedium,trailing?:React.ReactNode)=>{const active=activeWorkspace===id;return <button onClick={()=>onSelectWorkspace(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-[14px] transition ${active?"bg-white text-[#4D5CFF] shadow-sm":"text-[#41464F] hover:bg-white/70"}`}><Icon size={18} strokeWidth={active?2.4:2}/><span className="flex-1 text-left font-semibold">{label}</span>{trailing}</button>};
 return <><aside className="flex h-full w-[264px] shrink-0 flex-col border-r border-[#E3E6ED] bg-[#EEF0F5]">
  <div className="flex items-center justify-between px-5 pb-3 pt-5"><button onClick={()=>setProfileOpen(true)} className="flex items-center gap-2 text-left"><span className="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-[#EC6392] via-[#CB6CDA] to-[#618AFF] text-white"><Sparkles size={17}/></span><span className="text-[16px] font-bold">Memo</span></button><div className="flex"><button aria-label="搜索记忆和资料" onClick={onOpenSearch} className="p-2 text-[#6B7280] hover:text-[#4D5CFF]"><Search size={18}/></button><button aria-label="添加资料" onClick={onUploadFile} className="p-2 text-[#6B7280] hover:text-[#4D5CFF]"><Plus size={19}/></button></div></div>
  {isLoading&&<div className="mx-5 mb-2 flex items-center gap-2 text-[12px]"><img src={imgLoadingSpinner} width={16} className="animate-spin"/>Memo 正在整理...</div>}
  <nav className="flex-1 space-y-1 overflow-y-auto px-3 pb-5">{navButton("today","今日待办",SunMedium,<span className="text-[11px] text-[#9CA3AF]">{todayCount}</span>)}{scenario.id==="student"&&<p className="mb-1 mt-5 px-3 text-[9px] font-bold tracking-[.14em] text-[#A1A7B2]">{scenario.workspaceLabel}</p>}<div className={`${scenario.id==="common"?"mt-5":""} space-y-0.5`}>{subjects.slice(0,5).map((s,i)=><button key={s.id} onClick={()=>onSelectSubject(s.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-[14px] transition ${activeWorkspace==="course"&&activeSubject===s.id?"bg-white font-semibold text-[#4D5CFF] shadow-sm":"text-[#41464F] hover:bg-white/70"}`}><span className="h-2.5 w-2.5 rounded-full" style={{background:colors[i]}}/><span className="truncate font-semibold">{s.short}</span><span className="ml-auto text-[11px] text-[#9CA3AF]">{s.count}</span></button>)}</div></nav>
 </aside>{profileOpen&&<div onClick={()=>setProfileOpen(false)} className="fixed inset-0 z-[210] bg-black/20"><aside onClick={e=>e.stopPropagation()} className="ml-auto h-full w-[460px] overflow-y-auto bg-white p-6 shadow-2xl"><button onClick={()=>setProfileOpen(false)} className="text-[11px] text-[#4D5CFF]">← 返回</button><p className="mt-6 text-[10px] font-bold tracking-[.12em] text-[#8C93A3]">{p.eyebrow}</p><h2 className="mt-2 text-[22px] font-bold">{p.title}</h2><p className="mt-2 text-[12px] leading-6 text-[#626977]">{p.description}</p>
  <section className="mt-6 rounded-2xl bg-gradient-to-br from-[#F0F2FF] to-[#F8F5FF] p-5"><small className="font-semibold text-[#6973C9]">{p.goalLabel}</small><b className="mt-2 block text-[15px]">{p.goal}</b><p className="mt-2 text-[10px] leading-5 text-[#737B90]">{p.goalDetail}</p></section>
  <h3 className="mt-6 text-[13px] font-bold">{p.statusTitle}</h3><div className="mt-3 grid grid-cols-2 gap-3">{p.status.map(x=><div key={x.label} className="rounded-2xl bg-[#F7F8FB] p-4"><small className="text-[#8A909C]">{x.label}</small><b className="mt-2 block text-[12px]">{x.value}</b><p className="mt-2 text-[9px] leading-4 text-[#9399A6]">{x.detail}</p></div>)}</div>
  <h3 className="mt-6 text-[13px] font-bold">{p.methodsTitle}</h3><div className="mt-3 space-y-2">{p.methods.map(x=><div key={x} className="rounded-xl bg-[#F7F8FB] px-4 py-3 text-[11px] text-[#555D6C]">{x}</div>)}</div><h3 className="mt-6 text-[13px] font-bold">{p.traitsTitle}</h3><div className="mt-3 flex flex-wrap gap-2">{p.traits.map(x=><span key={x} className="rounded-full bg-[#EEF0FF] px-3 py-1.5 text-[9px] font-semibold text-[#4D5CFF]">{x}</span>)}</div><section className="mt-6 rounded-2xl bg-[#FFF8E8] p-4"><small className="font-semibold text-[#B57A18]">需要留意</small><p className="mt-2 text-[11px] leading-5 text-[#705D38]">{p.warning}</p></section>
  <div className="mt-6 flex gap-2"><button onClick={()=>setEvidenceOpen(v=>!v)} className="rounded-xl bg-[#F1F3FF] px-4 py-2.5 text-[11px] font-semibold text-[#4D5CFF]">{evidenceOpen?"收起记忆依据":"查看记忆依据"}</button><button onClick={()=>setProfileCorrected(true)} className="rounded-xl bg-[#F5F6F8] px-4 py-2.5 text-[11px] font-semibold text-[#656D7B]">{profileCorrected?"已收到纠正 ✓":"纠正 Memo"}</button></div>{evidenceOpen&&<div className="mt-3 rounded-2xl border border-[#E7EAF0] p-4">{p.evidence.map(x=><div key={x} className="mt-2 text-[10px] leading-5 text-[#747B89]">• {x}</div>)}</div>}
 </aside></div>}</>;
}
